export const data = JSON.parse("{\"key\":\"v-7a9ea766\",\"path\":\"/guide/basic/guide%20-%20configuration.html\",\"title\":\"指南 - 配置\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"指南 - 配置\",\"shortTitle\":\"配置\",\"date\":\"2023-07-20T01:40:34.000Z\",\"order\":8,\"category\":[\"指南\"],\"tag\":[\"指南\"],\"description\":\"[[TOC]] 环境变量 配置文件 一共 四 个配置文件，都在平台根目录下，具体如下 ```text ├── .env # 基础环境变量配置文件（优先级最低） ├── .env.development # 开发环境变量配置文件 ├── .env.production # 生产环境变量配置文件 ├── .env.test # 测试环境变量配置文件 ```...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vue3-admin.youngkbt.cn/guide/basic/guide%20-%20configuration.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Kbt Admin Docs\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"指南 - 配置\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"[[TOC]] 环境变量 配置文件 一共 四 个配置文件，都在平台根目录下，具体如下 ```text ├── .env # 基础环境变量配置文件（优先级最低） ├── .env.development # 开发环境变量配置文件 ├── .env.production # 生产环境变量配置文件 ├── .env.test # 测试环境变量配置文件 ```...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Young Kbt\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"指南\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-07-20T01:40:34.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"指南 - 配置\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-07-20T01:40:34.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Young Kbt\\\",\\\"url\\\":\\\"https://youngkbt.cn\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"环境变量\",\"slug\":\"环境变量\",\"link\":\"#环境变量\",\"children\":[{\"level\":3,\"title\":\"配置文件\",\"slug\":\"配置文件\",\"link\":\"#配置文件\",\"children\":[]},{\"level\":3,\"title\":\"具体配置\",\"slug\":\"具体配置\",\"link\":\"#具体配置\",\"children\":[]},{\"level\":3,\"title\":\"基础用法\",\"slug\":\"基础用法\",\"link\":\"#基础用法\",\"children\":[]},{\"level\":3,\"title\":\"如何添加自定义配置\",\"slug\":\"如何添加自定义配置\",\"link\":\"#如何添加自定义配置\",\"children\":[]}]},{\"level\":2,\"title\":\"全局配置文件\",\"slug\":\"全局配置文件\",\"link\":\"#全局配置文件\",\"children\":[{\"level\":3,\"title\":\"基础用法\",\"slug\":\"基础用法-1\",\"link\":\"#基础用法-1\",\"children\":[]},{\"level\":3,\"title\":\"添加自定义配置\",\"slug\":\"添加自定义配置\",\"link\":\"#添加自定义配置\",\"children\":[]},{\"level\":3,\"title\":\"添加分类\",\"slug\":\"添加分类\",\"link\":\"#添加分类\",\"children\":[]}]}],\"readingTime\":{\"minutes\":5.65,\"words\":1696},\"filePathRelative\":\"guide/basic/guide - configuration.md\",\"localizedDate\":\"2023年7月20日\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
