export const data = JSON.parse("{\"key\":\"v-1a60e970\",\"path\":\"/guide/basic/guide-request.html\",\"title\":\"指南 - 请求\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"指南 - 请求\",\"shortTitle\":\"请求\",\"date\":\"2023-07-20T01:41:02.000Z\",\"order\":14,\"category\":[\"指南\"],\"tag\":[\"指南\"],\"description\":\"[[TOC]] 介绍 Admin 基于 Axios 封装了一套开箱即用的 http 请求。包括请求 Loading、错误处理、取消请求等功能，在 src/config/request 目录下。 中文文档 点击查看 Axios 中文文档 (https://www.axios-http.cn/) 配置 你需要手动配置你的 baseURL，`baseURL ...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vue3-admin.youngkbt.cn/guide/basic/guide-request.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Kbt Admin Docs\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"指南 - 请求\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"[[TOC]] 介绍 Admin 基于 Axios 封装了一套开箱即用的 http 请求。包括请求 Loading、错误处理、取消请求等功能，在 src/config/request 目录下。 中文文档 点击查看 Axios 中文文档 (https://www.axios-http.cn/) 配置 你需要手动配置你的 baseURL，`baseURL ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Young Kbt\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"指南\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-07-20T01:41:02.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"指南 - 请求\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-07-20T01:41:02.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Young Kbt\\\",\\\"url\\\":\\\"https://youngkbt.cn\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"介绍\",\"slug\":\"介绍\",\"link\":\"#介绍\",\"children\":[{\"level\":3,\"title\":\"中文文档\",\"slug\":\"中文文档\",\"link\":\"#中文文档\",\"children\":[]}]},{\"level\":2,\"title\":\"配置\",\"slug\":\"配置\",\"link\":\"#配置\",\"children\":[]},{\"level\":2,\"title\":\"基本使用\",\"slug\":\"基本使用\",\"link\":\"#基本使用\",\"children\":[{\"level\":3,\"title\":\"get\",\"slug\":\"get\",\"link\":\"#get\",\"children\":[]},{\"level\":3,\"title\":\"其他\",\"slug\":\"其他\",\"link\":\"#其他\",\"children\":[]},{\"level\":3,\"title\":\"完整写法\",\"slug\":\"完整写法\",\"link\":\"#完整写法\",\"children\":[]}]},{\"level\":2,\"title\":\"ContentType 封装\",\"slug\":\"contenttype-封装\",\"link\":\"#contenttype-封装\",\"children\":[]},{\"level\":2,\"title\":\"数组封装\",\"slug\":\"数组封装\",\"link\":\"#数组封装\",\"children\":[]},{\"level\":2,\"title\":\"Loading 封装\",\"slug\":\"loading-封装\",\"link\":\"#loading-封装\",\"children\":[]},{\"level\":2,\"title\":\"映射封装\",\"slug\":\"映射封装\",\"link\":\"#映射封装\",\"children\":[]},{\"level\":2,\"title\":\"请求异常封装\",\"slug\":\"请求异常封装\",\"link\":\"#请求异常封装\",\"children\":[]}],\"readingTime\":{\"minutes\":5.12,\"words\":1535},\"filePathRelative\":\"guide/basic/guide-request.md\",\"localizedDate\":\"2023年7月20日\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
