export const data = JSON.parse("{\"key\":\"v-2bbd9a49\",\"path\":\"/guide/basic/guide-build.html\",\"title\":\"指南 - 打包\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"指南 - 打包\",\"shortTitle\":\"打包\",\"date\":\"2023-07-20T01:41:12.000Z\",\"order\":16,\"category\":[\"指南\"],\"tag\":[\"指南\"],\"description\":\"[[TOC]] 打包命令 本地环境打包预览 ```sh yarn preview:build ``` 测试环境打包 ```sh yarn build:test ``` 正式环境打包 ```sh yarn build yarn build:prod ``` 打包分析 ```sh yarn report ``` 打包压缩 Admin 内置打包压缩功能，可以...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vue3-admin.youngkbt.cn/guide/basic/guide-build.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Kbt Admin Docs\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"指南 - 打包\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"[[TOC]] 打包命令 本地环境打包预览 ```sh yarn preview:build ``` 测试环境打包 ```sh yarn build:test ``` 正式环境打包 ```sh yarn build yarn build:prod ``` 打包分析 ```sh yarn report ``` 打包压缩 Admin 内置打包压缩功能，可以...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Young Kbt\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"指南\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-07-20T01:41:12.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"指南 - 打包\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-07-20T01:41:12.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Young Kbt\\\",\\\"url\\\":\\\"https://youngkbt.cn\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"打包命令\",\"slug\":\"打包命令\",\"link\":\"#打包命令\",\"children\":[{\"level\":3,\"title\":\"本地环境打包预览\",\"slug\":\"本地环境打包预览\",\"link\":\"#本地环境打包预览\",\"children\":[]},{\"level\":3,\"title\":\"测试环境打包\",\"slug\":\"测试环境打包\",\"link\":\"#测试环境打包\",\"children\":[]},{\"level\":3,\"title\":\"正式环境打包\",\"slug\":\"正式环境打包\",\"link\":\"#正式环境打包\",\"children\":[]},{\"level\":3,\"title\":\"打包分析\",\"slug\":\"打包分析\",\"link\":\"#打包分析\",\"children\":[]}]},{\"level\":2,\"title\":\"打包压缩\",\"slug\":\"打包压缩\",\"link\":\"#打包压缩\",\"children\":[]},{\"level\":2,\"title\":\"打包内容\",\"slug\":\"打包内容\",\"link\":\"#打包内容\",\"children\":[]}],\"readingTime\":{\"minutes\":1.38,\"words\":413},\"filePathRelative\":\"guide/basic/guide-build.md\",\"localizedDate\":\"2023年7月20日\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
