export const data = JSON.parse("{\"key\":\"v-7a98c891\",\"path\":\"/guide/basic/guide-layout.html\",\"title\":\"指南 - 布局\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"指南 - 布局\",\"shortTitle\":\"布局\",\"date\":\"2023-07-20T01:40:44.000Z\",\"order\":10,\"category\":[\"指南\"],\"tag\":[\"指南\"],\"description\":\"[[TOC]] 布局 Admin 的布局组件有顶栏、侧边菜单栏、标签栏、内容区，位于 src/layout 下，分别位为 components 目录的 Header、Menu、TabsNav、MainContent 下。 内容区（MainContent）根据路由进行组件的跳转，可视化页面的组件在 src/views 下。 布局支持 6 种形式动态切换，...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vue3-admin.youngkbt.cn/guide/basic/guide-layout.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Kbt Admin Docs\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"指南 - 布局\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"[[TOC]] 布局 Admin 的布局组件有顶栏、侧边菜单栏、标签栏、内容区，位于 src/layout 下，分别位为 components 目录的 Header、Menu、TabsNav、MainContent 下。 内容区（MainContent）根据路由进行组件的跳转，可视化页面的组件在 src/views 下。 布局支持 6 种形式动态切换，...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Young Kbt\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"指南\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-07-20T01:40:44.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"指南 - 布局\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-07-20T01:40:44.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Young Kbt\\\",\\\"url\\\":\\\"https://youngkbt.cn\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"布局\",\"slug\":\"布局\",\"link\":\"#布局\",\"children\":[]},{\"level\":2,\"title\":\"标签栏\",\"slug\":\"标签栏\",\"link\":\"#标签栏\",\"children\":[]},{\"level\":2,\"title\":\"页面刷新\",\"slug\":\"页面刷新\",\"link\":\"#页面刷新\",\"children\":[{\"level\":3,\"title\":\"方法一\",\"slug\":\"方法一\",\"link\":\"#方法一\",\"children\":[]},{\"level\":3,\"title\":\"方法二\",\"slug\":\"方法二\",\"link\":\"#方法二\",\"children\":[]},{\"level\":3,\"title\":\"状态管理 Pinia\",\"slug\":\"状态管理-pinia\",\"link\":\"#状态管理-pinia\",\"children\":[]},{\"level\":3,\"title\":\"事件总栈\",\"slug\":\"事件总栈\",\"link\":\"#事件总栈\",\"children\":[]},{\"level\":3,\"title\":\"错误日志\",\"slug\":\"错误日志\",\"link\":\"#错误日志\",\"children\":[]},{\"level\":3,\"title\":\"工具\",\"slug\":\"工具\",\"link\":\"#工具\",\"children\":[]}]},{\"level\":2,\"title\":\"进度条\",\"slug\":\"进度条\",\"link\":\"#进度条\",\"children\":[]},{\"level\":2,\"title\":\"版本号缓存\",\"slug\":\"版本号缓存\",\"link\":\"#版本号缓存\",\"children\":[]}],\"readingTime\":{\"minutes\":6.79,\"words\":2038},\"filePathRelative\":\"guide/basic/guide-layout.md\",\"localizedDate\":\"2023年7月20日\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
