export const data = JSON.parse("{\"key\":\"v-060d4ae7\",\"path\":\"/guide/advanced/advanced-auth.html\",\"title\":\"指南 - 权限管控\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"指南 - 权限管控\",\"shortTitle\":\"权限管控\",\"date\":\"2023-07-21T00:42:31.000Z\",\"order\":8,\"category\":[\"指南\"],\"tag\":[\"指南\"],\"description\":\"[[TOC]] 介绍 Admin 基于 RBAC 内置权限管控，RBAC（Role Based Access Control）权限指的是基于角色的访问控制。 权限管控分为路由权限和页面权限，也成为粗粒度权限和细粒度权限。 角色权限 角色权限是一个数组，支持多个角色进行权限管控。 路由角色权限 在 指南 - 路由 (/guide/basic/guide-...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vue3-admin.youngkbt.cn/guide/advanced/advanced-auth.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Kbt Admin Docs\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"指南 - 权限管控\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"[[TOC]] 介绍 Admin 基于 RBAC 内置权限管控，RBAC（Role Based Access Control）权限指的是基于角色的访问控制。 权限管控分为路由权限和页面权限，也成为粗粒度权限和细粒度权限。 角色权限 角色权限是一个数组，支持多个角色进行权限管控。 路由角色权限 在 指南 - 路由 (/guide/basic/guide-...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Young Kbt\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"指南\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-07-21T00:42:31.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"指南 - 权限管控\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-07-21T00:42:31.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Young Kbt\\\",\\\"url\\\":\\\"https://youngkbt.cn\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"介绍\",\"slug\":\"介绍\",\"link\":\"#介绍\",\"children\":[]},{\"level\":2,\"title\":\"角色权限\",\"slug\":\"角色权限\",\"link\":\"#角色权限\",\"children\":[{\"level\":3,\"title\":\"路由角色权限\",\"slug\":\"路由角色权限\",\"link\":\"#路由角色权限\",\"children\":[]},{\"level\":3,\"title\":\"页面角色权限\",\"slug\":\"页面角色权限\",\"link\":\"#页面角色权限\",\"children\":[]},{\"level\":3,\"title\":\"场景\",\"slug\":\"场景\",\"link\":\"#场景\",\"children\":[]}]},{\"level\":2,\"title\":\"认证权限\",\"slug\":\"认证权限\",\"link\":\"#认证权限\",\"children\":[{\"level\":3,\"title\":\"页面认证权限\",\"slug\":\"页面认证权限\",\"link\":\"#页面认证权限\",\"children\":[]},{\"level\":3,\"title\":\"场景\",\"slug\":\"场景-1\",\"link\":\"#场景-1\",\"children\":[]}]},{\"level\":2,\"title\":\"官方形式\",\"slug\":\"官方形式\",\"link\":\"#官方形式\",\"children\":[]},{\"level\":2,\"title\":\"角色和认证区别\",\"slug\":\"角色和认证区别\",\"link\":\"#角色和认证区别\",\"children\":[]},{\"level\":2,\"title\":\"数据权限\",\"slug\":\"数据权限\",\"link\":\"#数据权限\",\"children\":[]}],\"readingTime\":{\"minutes\":5.9,\"words\":1771},\"filePathRelative\":\"guide/advanced/advanced-auth.md\",\"localizedDate\":\"2023年7月21日\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
