export const data = JSON.parse("{\"key\":\"v-b0205110\",\"path\":\"/guide/advanced/advanced-vite-config.html\",\"title\":\"指南 - Vite 配置\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"指南 - Vite 配置\",\"shortTitle\":\"Vite 配置\",\"date\":\"2023-07-31T23:53:12.000Z\",\"order\":14,\"category\":[\"指南\"],\"tag\":[\"指南\"],\"description\":\"[[TOC]] 介绍 下面介绍下 Admin 的 vite.config.ts 的内容。 vite.config.ts 是 Vite 构建、打包的核心配置文件。 Vite 官方文档 (https://cn.vitejs.dev/) 环境变量 Admin 在 vite.config.ts 文件里封装了一个文件来获取环境变量，文件路径为 /build/ge...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vue3-admin.youngkbt.cn/guide/advanced/advanced-vite-config.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Kbt Admin Docs\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"指南 - Vite 配置\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"[[TOC]] 介绍 下面介绍下 Admin 的 vite.config.ts 的内容。 vite.config.ts 是 Vite 构建、打包的核心配置文件。 Vite 官方文档 (https://cn.vitejs.dev/) 环境变量 Admin 在 vite.config.ts 文件里封装了一个文件来获取环境变量，文件路径为 /build/ge...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Young Kbt\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"指南\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-07-31T23:53:12.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"指南 - Vite 配置\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-07-31T23:53:12.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Young Kbt\\\",\\\"url\\\":\\\"https://youngkbt.cn\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"介绍\",\"slug\":\"介绍\",\"link\":\"#介绍\",\"children\":[]},{\"level\":2,\"title\":\"环境变量\",\"slug\":\"环境变量\",\"link\":\"#环境变量\",\"children\":[]},{\"level\":2,\"title\":\"@\",\"slug\":\"\",\"link\":\"#\",\"children\":[]},{\"level\":2,\"title\":\"plugins 插件\",\"slug\":\"plugins-插件\",\"link\":\"#plugins-插件\",\"children\":[{\"level\":3,\"title\":\"预构建\",\"slug\":\"预构建\",\"link\":\"#预构建\",\"children\":[]}]},{\"level\":2,\"title\":\"proxy 代理\",\"slug\":\"proxy-代理\",\"link\":\"#proxy-代理\",\"children\":[]},{\"level\":2,\"title\":\"css 全局注入\",\"slug\":\"css-全局注入\",\"link\":\"#css-全局注入\",\"children\":[]},{\"level\":2,\"title\":\"打包\",\"slug\":\"打包\",\"link\":\"#打包\",\"children\":[]},{\"level\":2,\"title\":\"Admin 信息\",\"slug\":\"admin-信息\",\"link\":\"#admin-信息\",\"children\":[]}],\"readingTime\":{\"minutes\":4.85,\"words\":1455},\"filePathRelative\":\"guide/advanced/advanced-vite-config.md\",\"localizedDate\":\"2023年8月1日\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
