export const data = JSON.parse("{\"key\":\"v-6337fdaa\",\"path\":\"/guide/advanced/advanced-typescript.html\",\"title\":\"指南 - TS 类型\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"指南 - TS 类型\",\"shortTitle\":\"TS 类型\",\"date\":\"2023-07-21T00:43:01.000Z\",\"order\":10,\"category\":[\"指南\"],\"tag\":[\"指南\"],\"description\":\"[[TOC]] 介绍 下面介绍 Admin 内置的 TS 声明文件（.d.ts 文件）和一些声明操作。 框架级别的 TS 声明文件在 src 目录下，项目级别的 TS 声明文件在 src/types 目录下。 TS 配置文件 TS 的配置文件为根目录下的 tsconfig.json 文件，Admin 已经在该文件里添加了项目需要的 .d.ts、`.ts...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vue3-admin.youngkbt.cn/guide/advanced/advanced-typescript.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Kbt Admin Docs\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"指南 - TS 类型\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"[[TOC]] 介绍 下面介绍 Admin 内置的 TS 声明文件（.d.ts 文件）和一些声明操作。 框架级别的 TS 声明文件在 src 目录下，项目级别的 TS 声明文件在 src/types 目录下。 TS 配置文件 TS 的配置文件为根目录下的 tsconfig.json 文件，Admin 已经在该文件里添加了项目需要的 .d.ts、`.ts...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Young Kbt\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"指南\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-07-21T00:43:01.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"指南 - TS 类型\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-07-21T00:43:01.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Young Kbt\\\",\\\"url\\\":\\\"https://youngkbt.cn\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"介绍\",\"slug\":\"介绍\",\"link\":\"#介绍\",\"children\":[]},{\"level\":2,\"title\":\"TS 配置文件\",\"slug\":\"ts-配置文件\",\"link\":\"#ts-配置文件\",\"children\":[]},{\"level\":2,\"title\":\"shims-vue.d.ts\",\"slug\":\"shims-vue-d-ts\",\"link\":\"#shims-vue-d-ts\",\"children\":[]},{\"level\":2,\"title\":\"auto-import.d.ts\",\"slug\":\"auto-import-d-ts\",\"link\":\"#auto-import-d-ts\",\"children\":[]},{\"level\":2,\"title\":\"types/plugins.d.ts\",\"slug\":\"types-plugins-d-ts\",\"link\":\"#types-plugins-d-ts\",\"children\":[]},{\"level\":2,\"title\":\"自定义全局组件 TS 提示\",\"slug\":\"自定义全局组件-ts-提示\",\"link\":\"#自定义全局组件-ts-提示\",\"children\":[]},{\"level\":2,\"title\":\"全局类型声明\",\"slug\":\"全局类型声明\",\"link\":\"#全局类型声明\",\"children\":[]},{\"level\":2,\"title\":\"自定义 TS API\",\"slug\":\"自定义-ts-api\",\"link\":\"#自定义-ts-api\",\"children\":[]},{\"level\":2,\"title\":\"types/http.d.ts\",\"slug\":\"types-http-d-ts\",\"link\":\"#types-http-d-ts\",\"children\":[]}],\"readingTime\":{\"minutes\":7.83,\"words\":2350},\"filePathRelative\":\"guide/advanced/advanced-typescript.md\",\"localizedDate\":\"2023年7月21日\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
