export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"主页","i":"home"},["/README.md"]],
  ["v-2d0a870d","/en/",{"y":"h","t":"Project home","i":"home"},["/en/README.md"]],
  ["v-fffb8e28","/guide/",{"y":"a","t":"指南","i":"lightbulb"},["/guide/README.md"]],
  ["v-49c25e56","/structure/",{"y":"a","t":"构建流程","s":"构建流程"},["/structure/README.md"]],
  ["v-2bc14542","/structure/sourceCode-layout.html",{"y":"a","t":"构建 - 布局构建","O":4,"s":"布局构建"},[":md"]],
  ["v-28067ca0","/structure/sourceCode-router.html",{"y":"a","t":"构建 - 路由构建","O":2,"s":"路由构建"},[":md"]],
  ["v-060d4ae7","/guide/advanced/advanced-auth.html",{"y":"a","t":"指南 - 权限管控","O":8,"s":"权限管控"},[":md"]],
  ["v-96afef9e","/guide/advanced/advanced-i18n.html",{"y":"a","t":"指南 - 国际化","O":4,"s":"国际化"},[":md"]],
  ["v-b1c790c2","/guide/advanced/advanced-pre-build.html",{"y":"a","t":"指南 - 预构建","O":12,"s":"预构建"},[":md"]],
  ["v-baf18e8c","/guide/advanced/advanced-theme.html",{"y":"a","t":"指南 - 主题样式","O":6,"s":"主题样式"},[":md"]],
  ["v-6337fdaa","/guide/advanced/advanced-typescript.html",{"y":"a","t":"指南 - TS 类型","O":10,"s":"TS 类型"},[":md"]],
  ["v-b0205110","/guide/advanced/advanced-vite-config.html",{"y":"a","t":"指南 - Vite 配置","O":14,"s":"Vite 配置"},[":md"]],
  ["v-7676ace1","/guide/advanced/",{"y":"a","t":"进阶","i":"lightbulb"},["/guide/advanced/README.md"]],
  ["v-2bbd9a49","/guide/basic/guide-build.html",{"y":"a","t":"指南 - 打包","O":16,"s":"打包"},[":md"]],
  ["v-15407a7e","/guide/basic/guide-configuration.html",{"y":"a","t":"指南 - 配置","O":8,"s":"配置"},[":md"]],
  ["v-3605d8f7","/guide/basic/guide-directives.html",{"y":"a","t":"指南 - 指令","O":20,"s":"指令"},[":md"]],
  ["v-6104aaaa","/guide/basic/guide-directory.html",{"y":"a","t":"指南 - 目录结构","O":6,"s":"目录结构"},[":md"]],
  ["v-74bc1f38","/guide/basic/guide-introduce.html",{"y":"a","t":"指南 - 介绍","O":2,"s":"介绍"},[":md"]],
  ["v-7a98c891","/guide/basic/guide-layout.html",{"y":"a","t":"指南 - 布局","O":10,"s":"布局"},[":md"]],
  ["v-5bdb2635","/guide/basic/guide-quick-start.html",{"y":"a","t":"指南 - 快速开始","O":4,"s":"快速开始"},[":md"]],
  ["v-1a60e970","/guide/basic/guide-request.html",{"y":"a","t":"指南 - 请求","O":14,"s":"请求"},[":md"]],
  ["v-7e2edf4e","/guide/basic/guide-route.html",{"y":"a","t":"指南 - 路由","O":12,"s":"路由"},[":md"]],
  ["v-7702eca6","/guide/basic/",{"y":"a","t":"基础","i":"lightbulb"},["/guide/basic/README.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
]
